namespace GBEmulator.App;

using Core.Enums;
using Core.Models;

public class InstructionHelper
{
    private static readonly Instruction[] Instructions = {
        new() {  Opcode = 0x00, Type = InstructionType.NOP, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x01, Type = InstructionType.LD, NumberOfBytes = 3, NumberOfCycles = 3, Param1 = InstructionParam.BC, Param2 = InstructionParam.d16 },
        new() {  Opcode = 0x02, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.BCMem, Param2 = InstructionParam.A },
        new() {  Opcode = 0x03, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.BC, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x04, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x05, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x06, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.B, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0x07, Type = InstructionType.RLCA, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x08, Type = InstructionType.LD, NumberOfBytes = 3, NumberOfCycles = 5, Param1 = InstructionParam.a16Mem, Param2 = InstructionParam.SP },
        new() {  Opcode = 0x09, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HL, Param2 = InstructionParam.BC },
        new() {  Opcode = 0x0A, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.BCMem },
        new() {  Opcode = 0x0B, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.BC, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x0C, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x0D, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x0E, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.C, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0x0F, Type = InstructionType.RRCA, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x10, Type = InstructionType.STOP, NumberOfBytes = 2, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x11, Type = InstructionType.LD, NumberOfBytes = 3, NumberOfCycles = 3, Param1 = InstructionParam.DE, Param2 = InstructionParam.d16 },
        new() {  Opcode = 0x12, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.DEMem, Param2 = InstructionParam.A },
        new() {  Opcode = 0x13, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.DE, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x14, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x15, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x16, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.D, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0x17, Type = InstructionType.RLA, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x18, Type = InstructionType.JR, NumberOfBytes = 2, NumberOfCycles = 3, Param1 = InstructionParam.s8, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x19, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HL, Param2 = InstructionParam.DE },
        new() {  Opcode = 0x1A, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.DEMem },
        new() {  Opcode = 0x1B, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.DE, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x1C, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x1D, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x1E, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.E, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0x1F, Type = InstructionType.RRA, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x20, Type = InstructionType.JR, NumberOfBytes = 2, NumberOfCycles = 3, Param1 = InstructionParam.NZ, Param2 = InstructionParam.s8 },
        new() {  Opcode = 0x21, Type = InstructionType.LD, NumberOfBytes = 3, NumberOfCycles = 3, Param1 = InstructionParam.HL, Param2 = InstructionParam.d16 },
        new() {  Opcode = 0x22, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLIMem, Param2 = InstructionParam.A },
        new() {  Opcode = 0x23, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HL, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x24, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x25, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x26, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.H, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0x27, Type = InstructionType.DAA, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x28, Type = InstructionType.JR, NumberOfBytes = 2, NumberOfCycles = 3, Param1 = InstructionParam.Z, Param2 = InstructionParam.s8 },
        new() {  Opcode = 0x29, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HL, Param2 = InstructionParam.HL },
        new() {  Opcode = 0x2A, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.HLIMem },
        new() {  Opcode = 0x2B, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HL, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x2C, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x2D, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x2E, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.L, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0x2F, Type = InstructionType.CPL, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x30, Type = InstructionType.JR, NumberOfBytes = 2, NumberOfCycles = 3, Param1 = InstructionParam.NC, Param2 = InstructionParam.s8 },
        new() {  Opcode = 0x31, Type = InstructionType.LD, NumberOfBytes = 3, NumberOfCycles = 3, Param1 = InstructionParam.SP, Param2 = InstructionParam.d16 },
        new() {  Opcode = 0x32, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLDMem, Param2 = InstructionParam.A },
        new() {  Opcode = 0x33, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.SP, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x34, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 3, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x35, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 3, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x36, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 3, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0x37, Type = InstructionType.SCF, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x38, Type = InstructionType.JR, NumberOfBytes = 2, NumberOfCycles = 3/2, Param1 = InstructionParam.C, Param2 = InstructionParam.s8 },
        new() {  Opcode = 0x39, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HL, Param2 = InstructionParam.SP },
        new() {  Opcode = 0x3A, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.HLDMem },
        new() {  Opcode = 0x3B, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.SP, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x3C, Type = InstructionType.INC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x3D, Type = InstructionType.DEC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x3E, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0x3F, Type = InstructionType.CCF, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x40, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.B },
        new() {  Opcode = 0x41, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.C },
        new() {  Opcode = 0x42, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.D },
        new() {  Opcode = 0x43, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.E },
        new() {  Opcode = 0x44, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.H },
        new() {  Opcode = 0x45, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.L },
        new() {  Opcode = 0x46, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.B, Param2 = InstructionParam.HLMem },
        new() {  Opcode = 0x47, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.A },
        new() {  Opcode = 0x48, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.B },
        new() {  Opcode = 0x49, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.C },
        new() {  Opcode = 0x4A, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.D },
        new() {  Opcode = 0x4B, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.E },
        new() {  Opcode = 0x4C, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.H },
        new() {  Opcode = 0x4D, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.L },
        new() {  Opcode = 0x4E, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.C, Param2 = InstructionParam.HLMem },
        new() {  Opcode = 0x4F, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.A },
        new() {  Opcode = 0x50, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.B },
        new() {  Opcode = 0x51, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.C },
        new() {  Opcode = 0x52, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.D },
        new() {  Opcode = 0x53, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.E },
        new() {  Opcode = 0x54, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.H },
        new() {  Opcode = 0x55, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.L },
        new() {  Opcode = 0x56, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.D, Param2 = InstructionParam.HLMem },
        new() {  Opcode = 0x57, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.A },
        new() {  Opcode = 0x58, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.B },
        new() {  Opcode = 0x59, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.C },
        new() {  Opcode = 0x5A, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.D },
        new() {  Opcode = 0x5B, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.E },
        new() {  Opcode = 0x5C, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.H },
        new() {  Opcode = 0x5D, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.L },
        new() {  Opcode = 0x5E, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.E, Param2 = InstructionParam.HLMem },
        new() {  Opcode = 0x5F, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.A },
        new() {  Opcode = 0x60, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.B },
        new() {  Opcode = 0x61, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.C },
        new() {  Opcode = 0x62, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.D },
        new() {  Opcode = 0x63, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.E },
        new() {  Opcode = 0x64, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.H },
        new() {  Opcode = 0x65, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.L },
        new() {  Opcode = 0x66, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.H, Param2 = InstructionParam.HLMem },
        new() {  Opcode = 0x67, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.A },
        new() {  Opcode = 0x68, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.B },
        new() {  Opcode = 0x69, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.C },
        new() {  Opcode = 0x6A, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.D },
        new() {  Opcode = 0x6B, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.E },
        new() {  Opcode = 0x6C, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.H },
        new() {  Opcode = 0x6D, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.L },
        new() {  Opcode = 0x6E, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.L, Param2 = InstructionParam.HLMem },
        new() {  Opcode = 0x6F, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.A },
        new() {  Opcode = 0x70, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.B },
        new() {  Opcode = 0x71, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.C },
        new() {  Opcode = 0x72, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.D },
        new() {  Opcode = 0x73, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.E },
        new() {  Opcode = 0x74, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.H },
        new() {  Opcode = 0x75, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.L },
        new() {  Opcode = 0x76, Type = InstructionType.HALT, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x77, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.A },
        new() {  Opcode = 0x78, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.B },
        new() {  Opcode = 0x79, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.C },
        new() {  Opcode = 0x7A, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.D },
        new() {  Opcode = 0x7B, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.E },
        new() {  Opcode = 0x7C, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.H },
        new() {  Opcode = 0x7D, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.L },
        new() {  Opcode = 0x7E, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.HLMem },
        new() {  Opcode = 0x7F, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.A },
        new() {  Opcode = 0x80, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.B },
        new() {  Opcode = 0x81, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.C },
        new() {  Opcode = 0x82, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.D },
        new() {  Opcode = 0x83, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.E },
        new() {  Opcode = 0x84, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.H },
        new() {  Opcode = 0x85, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.L },
        new() {  Opcode = 0x86, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.HLMem },
        new() {  Opcode = 0x87, Type = InstructionType.ADD, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.A },
        new() {  Opcode = 0x88, Type = InstructionType.ADC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.B },
        new() {  Opcode = 0x89, Type = InstructionType.ADC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.C },
        new() {  Opcode = 0x8A, Type = InstructionType.ADC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.D },
        new() {  Opcode = 0x8B, Type = InstructionType.ADC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.E },
        new() {  Opcode = 0x8C, Type = InstructionType.ADC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.H },
        new() {  Opcode = 0x8D, Type = InstructionType.ADC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.L },
        new() {  Opcode = 0x8E, Type = InstructionType.ADC, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.HLMem },
        new() {  Opcode = 0x8F, Type = InstructionType.ADC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.A },
        new() {  Opcode = 0x90, Type = InstructionType.SUB, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x91, Type = InstructionType.SUB, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x92, Type = InstructionType.SUB, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x93, Type = InstructionType.SUB, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x94, Type = InstructionType.SUB, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x95, Type = InstructionType.SUB, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x96, Type = InstructionType.SUB, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x97, Type = InstructionType.SUB, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0x98, Type = InstructionType.SBC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.B },
        new() {  Opcode = 0x99, Type = InstructionType.SBC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.C },
        new() {  Opcode = 0x9A, Type = InstructionType.SBC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.D },
        new() {  Opcode = 0x9B, Type = InstructionType.SBC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.E },
        new() {  Opcode = 0x9C, Type = InstructionType.SBC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.H },
        new() {  Opcode = 0x9D, Type = InstructionType.SBC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.L },
        new() {  Opcode = 0x9E, Type = InstructionType.SBC, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.HLMem },
        new() {  Opcode = 0x9F, Type = InstructionType.SBC, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.A },
        new() {  Opcode = 0xA0, Type = InstructionType.AND, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xA1, Type = InstructionType.AND, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xA2, Type = InstructionType.AND, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xA3, Type = InstructionType.AND, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xA4, Type = InstructionType.AND, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xA5, Type = InstructionType.AND, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xA6, Type = InstructionType.AND, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xA7, Type = InstructionType.AND, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xA8, Type = InstructionType.XOR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xA9, Type = InstructionType.XOR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xAA, Type = InstructionType.XOR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xAB, Type = InstructionType.XOR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xAC, Type = InstructionType.XOR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xAD, Type = InstructionType.XOR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xAE, Type = InstructionType.XOR, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xAF, Type = InstructionType.XOR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xB0, Type = InstructionType.OR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xB1, Type = InstructionType.OR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xB2, Type = InstructionType.OR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xB3, Type = InstructionType.OR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xB4, Type = InstructionType.OR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xB5, Type = InstructionType.OR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xB6, Type = InstructionType.OR, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xB7, Type = InstructionType.OR, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xB8, Type = InstructionType.CP, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.B, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xB9, Type = InstructionType.CP, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.C, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xBA, Type = InstructionType.CP, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.D, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xBB, Type = InstructionType.CP, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.E, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xBC, Type = InstructionType.CP, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.H, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xBD, Type = InstructionType.CP, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.L, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xBE, Type = InstructionType.CP, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.HLMem, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xBF, Type = InstructionType.CP, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.A, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xC0, Type = InstructionType.RET, NumberOfBytes = 1, NumberOfCycles = 5, Param1 = InstructionParam.NZ, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xC1, Type = InstructionType.POP, NumberOfBytes = 1, NumberOfCycles = 3, Param1 = InstructionParam.BC, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xC2, Type = InstructionType.JP, NumberOfBytes = 3, NumberOfCycles = 4, Param1 = InstructionParam.NZ, Param2 = InstructionParam.a16Mem },
        new() {  Opcode = 0xC3, Type = InstructionType.JP, NumberOfBytes = 3, NumberOfCycles = 4, Param1 = InstructionParam.a16Mem, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xC4, Type = InstructionType.CALL, NumberOfBytes = 3, NumberOfCycles = 6/3, Param1 = InstructionParam.NZ, Param2 = InstructionParam.a16Mem },
        new() {  Opcode = 0xC5, Type = InstructionType.PUSH, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.BC, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xC6, Type = InstructionType.ADD, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0xC7, Type = InstructionType.RST, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.Bit, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xC8, Type = InstructionType.RET, NumberOfBytes = 1, NumberOfCycles = 5, Param1 = InstructionParam.Z, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xC9, Type = InstructionType.RET, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xCA, Type = InstructionType.JP, NumberOfBytes = 3, NumberOfCycles = 4, Param1 = InstructionParam.Z, Param2 = InstructionParam.a16Mem },
        new() {  Opcode = 0xCC, Type = InstructionType.CALL, NumberOfBytes = 3, NumberOfCycles = 6/3, Param1 = InstructionParam.Z, Param2 = InstructionParam.a16Mem },
        new() {  Opcode = 0xCD, Type = InstructionType.CALL, NumberOfBytes = 3, NumberOfCycles = 6, Param1 = InstructionParam.a16Mem, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xCE, Type = InstructionType.ADC, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0xCF, Type = InstructionType.RST, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.Bit, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xD0, Type = InstructionType.RET, NumberOfBytes = 1, NumberOfCycles = 5/2, Param1 = InstructionParam.NC, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xD1, Type = InstructionType.POP, NumberOfBytes = 1, NumberOfCycles = 3, Param1 = InstructionParam.DE, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xD2, Type = InstructionType.JP, NumberOfBytes = 3, NumberOfCycles = 4, Param1 = InstructionParam.NC, Param2 = InstructionParam.a16Mem },
        new() {  Opcode = 0xD4, Type = InstructionType.CALL, NumberOfBytes = 3, NumberOfCycles = 6/3, Param1 = InstructionParam.NC, Param2 = InstructionParam.a16Mem },
        new() {  Opcode = 0xD5, Type = InstructionType.PUSH, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.DE, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xD6, Type = InstructionType.SUB, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.d8, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xD7, Type = InstructionType.RST, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.Bit, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xD8, Type = InstructionType.RET, NumberOfBytes = 1, NumberOfCycles = 5, Param1 = InstructionParam.C, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xD9, Type = InstructionType.RETI, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xDA, Type = InstructionType.JP, NumberOfBytes = 3, NumberOfCycles = 4, Param1 = InstructionParam.C, Param2 = InstructionParam.a16Mem },
        new() {  Opcode = 0xDC, Type = InstructionType.CALL, NumberOfBytes = 3, NumberOfCycles = 6/3, Param1 = InstructionParam.C, Param2 = InstructionParam.a16Mem },
        new() {  Opcode = 0xDE, Type = InstructionType.SBC, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.d8 },
        new() {  Opcode = 0xDF, Type = InstructionType.RST, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.Bit, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xE0, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 3, Param1 = InstructionParam.a8Mem, Param2 = InstructionParam.A },
        new() {  Opcode = 0xE1, Type = InstructionType.POP, NumberOfBytes = 1, NumberOfCycles = 3, Param1 = InstructionParam.HL, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xE2, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.CMem, Param2 = InstructionParam.A },
        new() {  Opcode = 0xE5, Type = InstructionType.PUSH, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.HL, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xE6, Type = InstructionType.AND, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.d8, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xE7, Type = InstructionType.RST, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.Bit, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xE8, Type = InstructionType.ADD, NumberOfBytes = 2, NumberOfCycles = 4, Param1 = InstructionParam.SP, Param2 = InstructionParam.s8 },
        new() {  Opcode = 0xE9, Type = InstructionType.JP, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.HL, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xEA, Type = InstructionType.LD, NumberOfBytes = 3, NumberOfCycles = 4, Param1 = InstructionParam.a16Mem, Param2 = InstructionParam.A },
        new() {  Opcode = 0xEE, Type = InstructionType.XOR, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.d8, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xEF, Type = InstructionType.RST, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.Bit, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xF0, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 3, Param1 = InstructionParam.A, Param2 = InstructionParam.a8Mem },
        new() {  Opcode = 0xF1, Type = InstructionType.POP, NumberOfBytes = 1, NumberOfCycles = 3, Param1 = InstructionParam.AF, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xF2, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.A, Param2 = InstructionParam.CMem },
        new() {  Opcode = 0xF3, Type = InstructionType.DI, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xF5, Type = InstructionType.PUSH, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.AF, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xF6, Type = InstructionType.OR, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.d8, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xF7, Type = InstructionType.RST, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.Bit, Param2 = InstructionParam.NoParameter },
        //new() {  Opcode = 0xF8, Type = InstructionType.LD, NumberOfBytes = 2, NumberOfCycles = 3, Param1 = InstructionParam.HL, Param2 = InstructionParam.SP+s8 },
        new() {  Opcode = 0xF9, Type = InstructionType.LD, NumberOfBytes = 1, NumberOfCycles = 2, Param1 = InstructionParam.SP, Param2 = InstructionParam.HL },
        new() {  Opcode = 0xFA, Type = InstructionType.LD, NumberOfBytes = 3, NumberOfCycles = 4, Param1 = InstructionParam.A, Param2 = InstructionParam.a16Mem },
        new() {  Opcode = 0xFB, Type = InstructionType.EI, NumberOfBytes = 1, NumberOfCycles = 1, Param1 = InstructionParam.NoParameter, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xFE, Type = InstructionType.CP, NumberOfBytes = 2, NumberOfCycles = 2, Param1 = InstructionParam.d8, Param2 = InstructionParam.NoParameter },
        new() {  Opcode = 0xFF, Type = InstructionType.RST, NumberOfBytes = 1, NumberOfCycles = 4, Param1 = InstructionParam.Bit, Param2 = InstructionParam.NoParameter },
    };

    public static Lookup<byte, Instruction> Lookup => (Lookup<byte, Instruction>)Instructions.ToLookup(instruction => instruction.Opcode, instruction => instruction);
}

public static class InstructionParamHelperExtensions
{
    private static IEnumerable<InstructionParam> _registers = new List<InstructionParam>
    {
        InstructionParam.A, InstructionParam.B, InstructionParam.C, InstructionParam.D,
        InstructionParam.E, InstructionParam.H, InstructionParam.L, InstructionParam.SP,
        InstructionParam.PC, InstructionParam.BC, InstructionParam.DE, InstructionParam.HL
    };

    private static IEnumerable<InstructionParam> _memoryLocations = new List<InstructionParam>
    {
        InstructionParam.a16Mem, InstructionParam.BCMem, InstructionParam.DEMem, InstructionParam.HLMem,
        InstructionParam.HLIMem, InstructionParam.HLDMem,
    };

    private static IEnumerable<InstructionParam> _values = new List<InstructionParam>
    {
        InstructionParam.d8, InstructionParam.d16
    };

    public static bool IsRegister(this InstructionParam instructionParam)
    {
        return _registers.Contains(instructionParam);
    }

    public static bool IsMemoryLocation(this InstructionParam instructionParam)
    {
        return _memoryLocations.Contains(instructionParam);
    }

    public static bool IsValue(this InstructionParam instructionParam)
    {
        return _values.Contains(instructionParam);
    }
}